# Generated by Django 4.0.4 on 2022-04-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_review_book_remove_review_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
